namespace Tangle.Net.Unit.Tests.Cryptography
{
  using Microsoft.VisualStudio.TestTools.UnitTesting;

  using Tangle.Net.Cryptography;
  using Tangle.Net.Cryptography.Curl;
  using Tangle.Net.Cryptography.Signing;
  using Tangle.Net.Entity;

  /// <summary>
  /// The signing helper test.
  /// </summary>
  [TestClass]
  public class SigningHelperTest
  {
    /// <summary>
    /// The test subseed generation.
    /// </summary>
    [TestMethod]
    public void TestSubseedGeneration()
    {
      var seed = new Seed("L9DRGFPYDMGVLH9ZCEWHXNEPC9TQQSA9W9FZVYXLBMJTHJC9HZDONEJMMVJVEMHWCIBLAUYBAUFQOMYSN");
      var expectedSubseedValue = "DXAAFFTM9LWSNRYTTCIHCNDVRHJBRKFGDHPAQSJWGHNLGBFJUXW9MELIMXTSUCUYEEBSXTEQHEPSTZWIL";
      var signingHelper = new IssSigningHelper(new Curl(CurlMode.CurlP27), new Curl(CurlMode.CurlP27), new Curl(CurlMode.CurlP27));

      var subseedTrits = signingHelper.GetSubseed(seed, 0);
      var subseed = Converter.TritsToTrytes(subseedTrits);

      Assert.AreEqual(expectedSubseedValue, subseed);
    }

    /// <summary>
    /// The test digest from subseed.
    /// </summary>
    [TestMethod]
    public void TestDigestFromSubseed()
    {
      var expectedDigest = "DFTTZXYAWRRKHMGYGIUEF9BUCQXXXGGMFZTLC9NKFPPL9HDOLSBITWNHMBZFSXIKIZCVL9KWBMTORBU9U";
      var subseed = new TryteString("DXAAFFTM9LWSNRYTTCIHCNDVRHJBRKFGDHPAQSJWGHNLGBFJUXW9MELIMXTSUCUYEEBSXTEQHEPSTZWIL");

      var signingHelper = new IssSigningHelper(new Curl(CurlMode.CurlP27), new Curl(CurlMode.CurlP27), new Curl(CurlMode.CurlP27));

      var digest = signingHelper.DigestFromSubseed(subseed.ToTrits(), SecurityLevel.Medium);
      var digestTrytes = Converter.TritsToTrytes(digest);

      Assert.AreEqual(expectedDigest, digestTrytes);
    }

    /// <summary>
    /// The test address from digest.
    /// </summary>
    [TestMethod]
    public void TestAddressFromDigest()
    {
      var expectedAddress = "MYNGVRBGNNKWHSTPOUOCBFWXKIUGZEYRCS9NGO9RYKLSOYAEBPOTNNONK9EVJTXQHYLOCRGCJWTTETSYA";
      var digest = new TryteString("DFTTZXYAWRRKHMGYGIUEF9BUCQXXXGGMFZTLC9NKFPPL9HDOLSBITWNHMBZFSXIKIZCVL9KWBMTORBU9U");

      var signingHelper = new IssSigningHelper(new Curl(CurlMode.CurlP27), new Curl(CurlMode.CurlP27), new Curl(CurlMode.CurlP27));

      var address = signingHelper.AddressFromDigest(digest.ToTrits());
      var addressTrytes = Converter.TritsToTrytes(address);

      Assert.AreEqual(expectedAddress, addressTrytes);
    }

    /// <summary>
    /// The test key from subseed.
    /// </summary>
    [TestMethod]
    public void TestKeyFromSubseed()
    {
      var subseed = new TryteString("DXAAFFTM9LWSNRYTTCIHCNDVRHJBRKFGDHPAQSJWGHNLGBFJUXW9MELIMXTSUCUYEEBSXTEQHEPSTZWIL");

      var signingHelper = new IssSigningHelper(new Curl(CurlMode.CurlP27), new Curl(CurlMode.CurlP27), new Curl(CurlMode.CurlP27));
      var privatekeyTrits = signingHelper.PrivateKeyFromSubseed(subseed.ToTrits(), SecurityLevel.Low);

      var privateKey = new TryteString(Converter.TritsToTrytes(privatekeyTrits));

      Assert.AreEqual(
        "GYKLRCZPZDHCVVGPMT9RQHRMDRNFIINSYTEWUHAVHNDXFHVXJRMEAMYCYSBDCOSRZGGBUODAOZJLYJJSGQKSHRBDFOVQVKEVTPZV9EJ9QTBXPKCEOZTLQZIURXPLIMSAPOZICILV9LEUKEUQGJSZUYFMFOLYFEFSO9UXHTAITJCFLQQXXLWQUJJYPESYLNFYJNOXCWKDGL9MAOFKMAPWBPAYJWRQSFCYPGLCBFTINRT9WX9FAKZKZMPEYTDUEPFNTJCEWCBMFIKTERGAVAEWNKXAHVAHYOJGDGKUDNQYUWVUJVEBGLUU9LJSIU9XWOPFCZBYOTGJZXTWSQFLVBSRDXRUKKTJZLZWWV9OENA9FWCHHDSDJTUNEVPMONAVWKGXDZCPUAZLLYF9PVMQFXEQQJSDSL99I9QUNQBANMSIMOWKRJIZOTDBZTJVEFJIIHXXFFXWZAGI9FAWOSOUYEKXLAUCGXEDGAJWSBDTOUMCFXYAQHDDUYJORICRAKKVUPLODIJNVJSJXHUXCYKSMMWPVKXDKVFPG9XYOUD9DEXUQOFCTEUTLRJYHSGTGRBEGL9SHAROXJNWFGLUQJRRUNVATRQNFX9EMNBYDRADXKOWFXPFFUEGOQFXDJKH9IXJYQORHHOAPITLO9VMZTXVBIPFHBMKDQYBLBSPQQYFHAC9GKISNGLUBONOOMFBHQGRVVJGIGZVWSSNQUZUDUVQNFCTRPNSNPKWXZCMTB9TMQKCQLPNADLFVF9YGPDDJ9BOYTQQIBSIMOXWYVSARUJ9HHAEMHQQSZABBQFHOLRXNVAXBSPFVBDNTPKDEMMBDXJRA9IIXBDTKVANJSEIYLJQZZZIUJTLPHSRROGRWWDHIQNLHOFTUTXAVBSPIBTUVLBASBJQECFMPSZPZTKXJRIAQDFTHLCHLEFJ9FKQETFUR9KTKCLZUQLMABXVGLYZ9VKBCC9LFQNHAVNK99MJDOUDFKBUNZEZP9CKBYLSZALE9MYNJXWYNANFRQCMYCGLDGPQEQDM9LQTLZXMPPQM9OHKESCIWMULWNCMG9GWFJYSRSQIUTJECY99SMHLTNIMJDNVJFBFGNTNDLHTXWVCRDU9WENROFOEKCPBEFLZTQNBWPVSFRYNPPOTFZQBNA9ZS9AFTCLE9HGWSXRUVSXBFYEZZJCOZNDEDZN99PNYQPIRKHPLWCULLMKMPUCWDGSZ9YWLOHROUCBNZCZQOFGACRSRTXFUSNPVWGSNSASKARIVBHCRUSXJKCXBDXEAPP9ACGB9XRNOJRGBHACFUU9KJCSSUJHTHBIGDWUAGUMGHZHCBMPVNRWOHCUBPXOWYR9IUPCYZJKRDLBANQIUWWECNWYENTBFLVARSRKDTRSPJHFVDETG9GHMTYG9EQYDFU9RAOIUXDLHTHBJEAHB9BUCIFC9RYMXHJTQMZIHPGZICOKXWSYEACRIMM99VFI9BOJIIZSTD9VWUFOXMJYWYF9QBUBVIEOIMZCRCPLNWY9ZSKURUZKMDJSUNJJOHUOXXFKGXEHWWMLQJXWYKRUWAJBBNNGXYKPFFMWHLJNCKFZUFPSLDEEQBXVWPPVYKVEBQLIZYOBYIGVZZLFTRMKSWSOJGVNOWVIGGNUSKXFOYBURZRTEBBCCOEZIGJIIMEXGB9DCBDKJ9CLHCXBBQ9KLISDQBCYRRVDEC9OIBIENAQOPQHLAPKUBGZQIECFANOCZAAAKMCSTHTRCWIRCCCPXFPIGSPTCMOZNBOHCCFQGWPVOOOGSVFNJXQ99YNYYNZ9EERVJRLFSIESISMOCTANXQGOKSSUWQARPBUHGENGDBSDPCDIQEDMINVPFWKDG9MDLCFBDEUDYCOCXFLYPUXXIMJGVVUTNKM9HNIFIFUXXHZTJJYTNERZQZCBLZTBZYIELRYNWQQDSPADAHFVKTKCPWICNBCZETENRIWGMDASAQTLQKOPPVCYVSNECDSCTDCCAGKU9YGARTNBY9WTIRBVBPIQQPJNRAMRNYUDGWHXAQNB9RQLQ9DSVOZ9SOIJPXYSKMGLPIHWVHYMAGH9MLPWDFRPRRTAGUKIPOKOAAHSTMATDKCBMSNHAEVBWSLEEQDT9HQSRTADARYLZPXPEWCGXQXRRTRMRYHQAYMWBHPVJELBFQRWRBVOULPCMGHVVUQMEMHKXYZKFHVPBCXBGAFSWMSA",
        privateKey.Value);
    }
  }
}