namespace Tangle.Net.Mam.Unit.Tests.Mam
{
  using System.Configuration;

  using Microsoft.VisualStudio.TestTools.UnitTesting;

  using Tangle.Net.Cryptography;
  using Tangle.Net.Entity;
  using Tangle.Net.Mam.Mam;
  using Tangle.Net.Mam.Merkle;
  using Tangle.Net.Utils;

  /// <summary>
  /// The mam channel test.
  /// </summary>
  [TestClass]
  public class MamChannelTest
  {
    /// <summary>
    /// The test public channel creation.
    /// </summary>
    [TestMethod]
    public void TestPublicChannelCreation()
    {
      var seed = new Seed("JETCPWLCYRM9XYQMMZIFZLDBZZEWRMRVGWGGNCUH9LFNEHKEMLXAVEOFFVOATCNKVKELNQFAGOVUNWEJI");
      var mamFactory = new CurlMamFactory(new Curl(), new CurlMask());
      var treeFactory = new CurlMerkleTreeFactory(new CurlMerkleNodeFactory(new Curl()), new CurlMerkleLeafFactory(new AddressGenerator(seed)));

      var channelFactory = new MamChannelFactory(mamFactory, new CurlMamParser(new CurlMask(), treeFactory),  treeFactory, new InMemoryIotaRepository());
      var channel = channelFactory.Create(Mode.Public, seed);

      Assert.AreEqual(seed.Value, channel.Seed.Value);
      Assert.AreEqual(Mode.Public, channel.Mode);
      Assert.AreEqual(SecurityLevel.Medium, channel.SecurityLevel);
    }

    /// <summary>
    /// The test restricted channel creation.
    /// </summary>
    [TestMethod]
    public void TestRestrictedChannelCreation()
    {
      var seed = new Seed("JETCPWLCYRM9XYQMMZIFZLDBZZEWRMRVGWGGNCUH9LFNEHKEMLXAVEOFFVOATCNKVKELNQFAGOVUNWEJI");
      var mamFactory = new CurlMamFactory(new Curl(), new CurlMask());
      var treeFactory = new CurlMerkleTreeFactory(new CurlMerkleNodeFactory(new Curl()), new CurlMerkleLeafFactory(new AddressGenerator(seed)));

      var channelFactory = new MamChannelFactory(mamFactory, new CurlMamParser(new CurlMask(), treeFactory), treeFactory, new InMemoryIotaRepository());
      var channelKey = new TryteString("NXRZEZIKWGKIYDPVBRKWLYTWLUVSDLDCHVVSVIWDCIUZRAKPJUIABQDZBV9EGTJWUFTIGAUT9STIENCBC");
      var channel = channelFactory.Create(Mode.Restricted, seed, SecurityLevel.Medium, channelKey);

      Assert.AreEqual(seed.Value, channel.Seed.Value);
      Assert.AreEqual(Mode.Restricted, channel.Mode);
      Assert.AreEqual(SecurityLevel.Medium, channel.SecurityLevel);
      Assert.AreEqual(channelKey.Value, channel.Key.Value);
      Assert.AreEqual(Hash.Empty.Value, channel.NextRoot.Value);
      Assert.AreEqual(0, channel.Index);
      Assert.AreEqual(0, channel.Start);
      Assert.AreEqual(1, channel.Count);
      Assert.AreEqual(1, channel.NextCount);
    }

    /// <summary>
    /// The test restricted message creation.
    /// </summary>
    [TestMethod]
    public void TestRestrictedMessageCreation()
    {
      var bundle = new Bundle();
      bundle.AddTransfer(new Transfer
                           {
                             Address = new Address(),
                             Message = new TryteString("HDVESUIAEXXGMAHQJWJOXBNAW9JVETYZHLZZOLYQFOGUYMOPTUTZXMWUMCPWQWICHHNFEDRNIYYHYHFKKBQNFTFGIUUFANTCGPROJWPDQBRCERRLTPRTTOKRDILSPQTT9DAPWEPOREZTKEUITHQDTGCKODRJ9L9ASAO9POGLWLF9HZMKFBNL9GUTHSQVVRWAJKYGQGCZLPBNAGDQNBCNSMUDPUSSJALZWRWZEQUBKJN9TXXZIACXO9B9IJVUUTKINJBGKOZAVYEUQOJWBVOMETHMRTTPYDLOSCJAIEPWZGFPYTKOPPBOZVIC9PMDIZDVSNXEHBKWQOSAWNIKCABUIEPLLPPTMGKXYRZZIZAQCLOKFIPVGJBJDPHVXUKCODNZQKOOVBGGSGGNZ9VVAZHGYDPPMAIIRKXY9HUWGIZSDBCVIHXNDYFNBLRJABDGWAYCA9MXQJQGCBKZAJWX9CKFNWZSHCOEWDLSFE9TOYGVGXSJ9QH9UDJAPULRXVZYAQZ9UASKC9ODLEKVTEOPWEQCL9JKUVWSWPMRVZLVZOMECIGTW9KX9LSKIQGZW9U9SODYYIRULGFTCWSSZBU9WR9MNKZVMENSNAADZKWI9WEMRJOVNXCJN9WEAOIYPCEKBVALBEBAXCKUQLGT9L9IGWDHAMRHGHXWYXFTQ999DMJSGSGI9LDBNAKECQTUZKFSCBZNCLMLZARGFI9ILNYLTAKQYNGADULJQOKAVKPPVYBPQCNEBDNYTGTIAMTORWZXILNLDS9D9GWWTEJUEI9EQXROQZQINYXNXDLNGDXMAVKHDBHEYYKXPDTMCUSXOVM9UJWTWMQZEBFQMUFWEKWRLPLDAWIVCQZUQKHCXTMFTMVGPQZIBCKYPNZHHEAQABZCHV9QXEIRCINIAAVUUJUUXNUFEVZGBSJBHGCURASMCJVAKZCIXWCAEOEEIRRTEIBCINEBFARKFEVZFTTQVAOMLCAOWXSVQIPQIMWXQUGZCUDVYRNYHROGWQOSIJQLBMXTQZNOFXUXSSEIDHSZZUXVCLK9LCXTSQTPIWZPZYZKBOWRBSGTHDQQUNLENTVPXDJMHFZDFRDVPEVTDWRVCBRZJWZXHIR9UDUZEDLCPQZOIYJFJCSBQ9GXSWDNFJZAQDVQMSYJIQNDRBXSPONTXYIVWCYNSEUMJ9BHG9PNA9PMNUHDESZQBPHF9VDZHOWHLT9YB9MRXRK99HLDMXPEYQJKLHPAZFBUTSXGRSOHPDUJP9HBCVULWUEJBKJVNXTRWMQCVOLHZIFVGWWAGEXQUQTFPCXZNQ9HXYHNRLUQZHPUYIHFMRVYXXBOQ9OJCKEPFRCRM9GMVDNDSZX9YIHUSIROYBVPWGRTHKRDQQKAOFZWFPXQ9SZGUFJJO9BICOZE9URKKANQDIZAUESLTPMLZFL9KVOZPZEPRJILWL9QJPV9MGWYCYBPHUNAYFSYTZ9SZORVQKJIQJTVGEJWJOQPSWYCSZIZRTEFHVUSOERW9MJYQO9RB9TSLXHVSKKAMYRNKGMAGMZEAQYF9LDCNEBTAQKOGJKPEZVGHLLQDBJMDWHXUDKRDVKRLWVNVUTYMHCE9W9TDSDYAWSWPNMIRRHOYFZMMGIOBLORMRJJBJGJDZ9ANGTHOTIWTGMXGHG99PACDVIXBPWVZ9IMLONQPJRVVWAZMFUUFYRHUQDSJXTG9XMUYNV9CHXMDVTUOVBCUVVAJJZZJ9ODIHHASRCTSNZ9JZRKUAVAN9SFUAJMKXAOCGGCMFW9WSEOTRJELFR9JVIFBGYGXLGHI9DTGXIBCYRETZAAZUVMYMRNDXCLZ9XSEQSQVM9OROCIEVPRJDVKLQIWMYLCWJPTMZOSXUFMYHCNXNYEOKRCVWGSOWAUOR9GISWVVTAEBQJZYSTR9WXHLFWTEFMDKFFLVJOIEQ9GFKKYDEFHFMCBJLXWOAQYHTYHCOLPZPCLQE9NLDCTVGTSKUHHQDLINTCSBUMB9H9YSKMMGZSXIBTFONOBDILOJNCFYHAUBDEFQAXXKSQWSNPZVDATGUDKLX9SCMXLQPOXWIBQ99NSKVFSJN9IIOMB9OWXDLBMNJPRQGXRXFLNZHGPTITBZIHWSRKBGF9LOQO9EZSSOEJTPZMO99FUU9CTNOOGLB99NGFTPYJJSLIZTJGLWUNYPSNYIZELPFYREIDHOXHXL9MNITVZWQCMSPQKRRGZXSYUMMBYJQSBKLJXDQIRA9OZOHDXX9TLAXTVDCQHSGVDRODE9BVYNRVFDHBVRQRSLDOZRZGJYEHRDQXBUSPSKPDRMPJIEYPMZHBHJHTIDJCSDZRMLY9HGIIJMTRHYMFDQVGDBNXOWUUBMBGSZEV9WXSLICQMHLEJIS99LROFCCZAHGVKYRQFYPQMCAOOXVSVUWOYOAHTPLGYV9MWEL9PAWSZZISEMQVQOUDETEUKZWZKOUOCASGARKXHOWRWVZGVB9MECLKLHVFFSSBVEHPWKVJFFRKWXBXNVMKQDGSBTKRAOKQJQOMTUESFHLLZPEUBQYGMHYYZBMMDSMSWRNZ9IFTYGOFBSBYHFVFOVQBFSTJSKZMVNGQIH9YTFIKVBFZZJNA9BJFKFWBDW9HURRH9KUCEUXEHERLNZDAUZPVZWACVUGRYQZTRRSRBEBEYFUIECAOXCHICBEKMPJFXQXIPO9WSSJAZOQNVOYVVFBYTPSGMUZNLXPBZTSQSHIQIFKHTVDUTKPREXTTHMDDANVGNDJNBOZCEV9AQLOD9RYPGMSGOIK9XG9CFLAKPQTYGJRWFVEAINGMDDWHIWSGSODWOUR9BAQ9BJEFE9DNYTGDIMZDUFEOLIEEKJKRJQHKOPDB9TGFGXVALDJCTYMTOF9ATJQLTMLZGQOATJMS9GBOC9MCCENTPGZLOCBECGHVNY9GCAIHSKMEDPZUSBRIUPRNEJMTUI9ALC9GAYUESHOLWYIFWJAKLKGZGZ9DFMZYONXZNPYWWMXOYJHHJGMAOQJSGGNHOMLHHLDWHTTCTHSUHJNFRDZBAAXRZIMUKFYHMKHHLZEVQPHPONZARIOGDIQPWUUFRPTIDMNOVW9FHMPQKSTGALPCJOADIJJJSNAJYSWGVQYDUVABB9QH9AJVBNK9ENFTYEQTXOQFZLUMAFUNHPYCIQZHULOKGNIODTYBYRYRCDJIGIMZPOP9NPFPXYTQFZUWTSLOPZCWDRBYJ9UZHEWDZBQWLNGYAX9IDMUCGILOFKXDGDHYWOPBYBHNBJNOCWPMYAZH9RYSFZFXVPTHAVVAOHTIHOYCRLDFIWDIVLZMYKHMDOCAVPIXIWVBBRAOLZMHUVUCSYFWWEWPFGPYAGKAFWYOFTZKYIAX9SRAYE9BYTDVYVIEQLSHKJGFGYGQJ9MDJHGPM9FLYYTEVTLEBCHRMHZJBSQGIIFLDNBKQUREEOJS9MVKYJBMJFQIOUZNO9EHBLSZUZRPQKKOWMPFPZASOI9NXGQI9BMXLPQNHXENHEMXKCYSARLJQMBMFOBZFTQL9AQ9RBNUXLFAIIQHQIKIWWAZNAHT9PRVVJWVKGLKSSTUEVCRTHXXBHXGHRWHZLCZPEEFUUKUFCCFLURFDM9PYXRKPWXUZFUPZ9CNORXBVEHIFIKWCDWMYXQZWYSHUGELMDJSSSNURPULA9VRNFDUDPNQGTLOXLVOSYDITDNPNUHNN9ZXAJJSOPIRRRVKMDVGEXPNOJMSGGDFYKRVUBQKO9SAOVAKNP9GHHLGUNLPRTKPTBIZBTZJQPCDMD9FVF9DJPFPWLLBHQJQJJQJPNSIPNGVWQJDQDFRVYUITZYRFSN9JLQQWXUXXB9ZTNGBDVPSHSHNVQYIPHGJOAOSKYTPHYNZISPUOS9UNVRJSUCHAZKFKLNFGTFKNVQHD9NFVLHGXBACANGJG9GZRDTDKEJCFEAONPXEKHJVCS9EZZHACZIKBMVRCR9VFXRVHZH9JQTAKPAMCBGMVPDBXULYXMPSPXMSFJHVRQXLWJYWHIZJCXSBJIPGTEMBAYLIHGXLLUJOPQTCGDYEYAZFELXZCSVLHQBLDLHKXMXCSTWFVAXTEEZHKNKIBILHCIFDMSKKOYNRURVYFGGLKZTUHBKMU9NOPAUCHQURMVQ9CTIGJSHRKGOYHPKDYIWUOKKAIIINCVDOGVPAKEEOEVPMYWFFYOJ9FJVIDYLFROIYGXIUFOTPTJBNRISULRVAOEFDWRMHIGZEDRBRFTVZMXKHRRSKNGSFEWF9FAJQTZPKXKWJVZCDAUGQAPBQFRUQXXFTAQVFPAE9RUQYNCLZRFQCQCHRTDVNVGIFADJNUVXEEEYVLQBYMBDDUQEQDRBVGITHZVKAPO9M9HNGQQAPBBESSRT9DIWIXQHFPTCWMVT"),
                             Tag = new Tag("ASDF"),
                             Timestamp = Timestamp.UnixSecondsTimestamp
                           });

      bundle.Finalize();
      bundle.Sign();

      var seed = new Seed("JETCPWLCYRM9XYQMMZIFZLDBZZEWRMRVGWGGNCUH9LFNEHKEMLXAVEOFFVOATCNKVKELNQFAGOVUNWEJI");  
      var mamFactory = new CurlMamFactory(new Curl(), new CurlMask());
      var treeFactory = new CurlMerkleTreeFactory(new CurlMerkleNodeFactory(new Curl()), new CurlMerkleLeafFactory(new AddressGenerator(seed)));

      var channelFactory = new MamChannelFactory(mamFactory, new CurlMamParser(new CurlMask(), treeFactory), treeFactory, new InMemoryIotaRepository());
      var channelKey = new TryteString("NXRZEZIKWGKIYDPVBRKWLYTWLUVSDLDCHVVSVIWDCIUZRAKPJUIABQDZBV9EGTJWUFTIGAUT9STIENCBC");
      var channel = channelFactory.Create(Mode.Restricted, seed, SecurityLevel.Medium, channelKey);

      var message = channel.CreateMessage(new TryteString("IREALLYWANTTHISTOWORKINCSHARPASWELLPLEASEMAKEITHAPPEN"));

      Assert.AreEqual("ILUOWHDESMHWKVHTRVOF9YERPLWCXEZPJBYGLWOHWCRWMCS9GHICAZTKEZVN9JYQLBIWVXKSTWNZIUAVV", message.Root.Value);
      Assert.AreEqual("HJEDRSLPPDMJQLDWQAGF9CFDVOQTTVXWDRGMVQ9YJYUAQFZWFZZEV9WUP9NVHVPIEHRKZ9UDGAULMHWBK", message.Address.Value);
      Assert.AreEqual("WRYIKYCOMNQKCPRMT99POCFEAPOEDHVKIDFI9FUFYNUOVHZHQPHYQJFRN9JNLXTKWZZMJECJCGSEZ9LIH", message.NextRoot.Value);

      Assert.AreEqual("WRYIKYCOMNQKCPRMT99POCFEAPOEDHVKIDFI9FUFYNUOVHZHQPHYQJFRN9JNLXTKWZZMJECJCGSEZ9LIH", channel.NextRoot.Value);

      for (var i = 0; i < bundle.Transactions.Count; i++)
      {
        Assert.AreEqual(bundle.Transactions[i].Fragment.Value, message.Payload.Transactions[i].Fragment.Value);
      }
    }
  }
}